# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_asovac',
            name='subarea_id',
            field=models.ManyToManyField(to='arbitrajes.Sub_area'),
        ),
    ]
