# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_asovac',
            name='monto_pagar_trabajo',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema_asovac',
            name='porcentaje_iva',
            field=models.SmallIntegerField(default=14),
            preserve_default=False,
        ),
    ]
