# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-01 16:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, max_length=150)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario_asovac',
            name='area_id',
        ),
        migrations.AddField(
            model_name='sistema_asovac',
            name='coordinador_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Usuario_asovac'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='estado_arbitraje',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='usuario_asovac',
            name='area',
            field=models.ManyToManyField(blank=True, to='main_app.Area'),
        ),
        migrations.AddField(
            model_name='usuario_asovac',
            name='sub_area',
            field=models.ManyToManyField(blank=True, to='main_app.Sub_area'),
        ),
    ]
