# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_rol_in_sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Rol')),
                ('sistema_asovac', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario_asovac',
            name='Sistema_asovac_id',
        ),
        migrations.RemoveField(
            model_name='usuario_asovac',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario_rol_in_sistema',
            name='usuario_asovac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Usuario_asovac'),
        ),
    ]
