# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-19 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_asovac',
            name='cabecera',
            field=models.CharField(default='https://i.imgur.com/G1PXYZU.jpg', max_length=255, verbose_name='URL Imagen de Cabecera'),
        ),
        migrations.AddField(
            model_name='sistema_asovac',
            name='color_fondo_pie',
            field=models.CharField(default='#222', max_length=7, validators=[django.core.validators.RegexValidator('^(\\#[a-fA-F0-9]{6}|\\#[a-fA-F0-9]{3})?$', 'Este es un c\xf3digo de color inv\xe1lido. Debe ser un c\xf3digo de color hexadecimal html ej. #000000')]),
        ),
        migrations.AddField(
            model_name='sistema_asovac',
            name='color_letras_pie',
            field=models.CharField(default='#FFF', max_length=7, validators=[django.core.validators.RegexValidator('^(\\#[a-fA-F0-9]{6}|\\#[a-fA-F0-9]{3})?$', 'Este es un c\xf3digo de color inv\xe1lido. Debe ser un c\xf3digo de color hexadecimal html ej. #000000')]),
        ),
    ]
