# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sub_area',
            name='codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
