# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=100)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario_asovac',
            name='area_id',
        ),
        migrations.AddField(
            model_name='usuario_asovac',
            name='area',
            field=models.ManyToManyField(blank=True, to='main_app.Area'),
        ),
        migrations.AddField(
            model_name='usuario_asovac',
            name='sub_area',
            field=models.ManyToManyField(blank=True, to='main_app.Sub_area'),
        ),
    ]
