# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_asovac',
            name='subarea_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Area'),
        ),
    ]
