# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181124_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_rol_in_sistema',
            name='sistema_asovac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac'),
        ),
    ]
