# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180901_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_asovac',
            name='area',
        ),
    ]
