# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_usuario_asovac_subarea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_asovac',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(blank=True, to='main_app.Sistema_asovac'),
        ),
        migrations.AlterField(
            model_name='usuario_asovac',
            name='rol',
            field=models.ManyToManyField(blank=True, to='main_app.Rol'),
        ),
        migrations.AlterField(
            model_name='usuario_asovac',
            name='subarea_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Sub_area'),
        ),
    ]
