# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180826_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_area',
            old_name='area_id',
            new_name='area',
        ),
    ]
