# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180815_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_asovac',
            old_name='subarea_id',
            new_name='area_id',
        ),
    ]
