# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180701_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_asovac',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
