# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180826_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sub_area',
            name='descripcion',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='sub_area',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
