# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190801_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema_asovac',
            name='autoridad1',
            field=models.CharField(default='Nombre Autoridad1,T\xedtulo en Organizaci\xf3n,Nombre Organizaci\xf3n', max_length=100),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='autoridad2',
            field=models.CharField(default='Nombre Autoridad2,T\xedtulo en Organizaci\xf3n,Nombre Organizaci\xf3n', max_length=100),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='firma1',
            field=models.ImageField(default='default/signature_sample.jpg', upload_to=main_app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='sistema_asovac',
            name='firma2',
            field=models.ImageField(default='default/signature_sample.jpg', upload_to=main_app.models.upload_to),
        ),
    ]
