# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190801_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_asovac',
            name='ciudad',
            field=models.CharField(default='Caracas', max_length=50),
        ),
        migrations.AddField(
            model_name='sistema_asovac',
            name='numero_romano',
            field=models.CharField(default='LXVII', max_length=15),
        ),
    ]
