# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-27 01:22
from __future__ import unicode_literals

from django.db import migrations

def load_default_data(apps, schema_editor):
    '''
    Se cargan en esta migracion los las instancias por defecto de los
    siguientes modelos: Areas, Subareas y Rol
    '''
    Area = apps.get_model('main_app', 'Area')
    Sub_area = apps.get_model('main_app', 'Sub_area')
    Rol = apps.get_model('main_app', 'Rol')

    # Creacion de Roles
    Rol.objects.get_or_create(nombre="Admin", descripcion="Administrador")
    Rol.objects.get_or_create(nombre="Coordinador General", descripcion="CG")
    Rol.objects.get_or_create(nombre="Coordinador de Área", descripcion="CA")
    Rol.objects.get_or_create(nombre="Árbitro de Subárea", descripcion="AS")
    Rol.objects.get_or_create(nombre="Autor", descripcion="Autor")

    # Carga de contenido para el area 1
    Area.objects.get_or_create(id=1, nombre="Biociencias", descripcion="-", codigo="BC")

    Sub_area.objects.get_or_create(nombre="Parasitología", descripcion="-", area_id=1, codigo="PAR")
    Sub_area.objects.get_or_create(nombre="Biología Molecular", descripcion="-", area_id=1, codigo="BMOL")
    Sub_area.objects.get_or_create(nombre="Bioquímica", descripcion="-", area_id=1, codigo="BQM")
    Sub_area.objects.get_or_create(nombre="Tecnología de Alimentos", descripcion="-", area_id=1, codigo="TCA")
    Sub_area.objects.get_or_create(nombre="Ecología", descripcion="-", area_id=1, codigo="ECO")
    Sub_area.objects.get_or_create(nombre="Medicina", descripcion="-", area_id=1, codigo="MED")
    Sub_area.objects.get_or_create(nombre="Inmunología", descripcion="-", area_id=1, codigo="INM")
    Sub_area.objects.get_or_create(nombre="Microbiología", descripcion="-", area_id=1, codigo="MICB")
    Sub_area.objects.get_or_create(nombre="Farmacología", descripcion="-", area_id=1, codigo="FMC")

    # Para cargar contenido para el area 2
    Area.objects.get_or_create(id=2, nombre="Ciencias Exactas", descripcion="-", codigo="CE")

    Sub_area.objects.get_or_create(nombre="Matemática", descripcion="-", area_id=2, codigo="MAT")
    Sub_area.objects.get_or_create(nombre="Química Organometálica", descripcion="-", area_id=2, codigo="OM")
    Sub_area.objects.get_or_create(nombre="Productos Naturales", descripcion="-", area_id=2, codigo="PN")
    Sub_area.objects.get_or_create(nombre="Farmacología", descripcion="-", area_id=2, codigo="FMC")
    Sub_area.objects.get_or_create(nombre="Nanosistemas", descripcion="-", area_id=2, codigo="NS")

    # Para cargar contenido para el area 3
    Area.objects.get_or_create(id=3,nombre="Tecnología",descripcion="-",codigo="TEC")

    Sub_area.objects.get_or_create(nombre="Computación",descripcion="-",area_id=3,codigo="COMP")
    Sub_area.objects.get_or_create(nombre="Ingeniería Electrónica y Biomédica",descripcion="-",area_id=3,codigo="IEB")

    # Para cargar contenido para el area 4
    Area.objects.get_or_create(id=4,nombre="Ciencias Sociales",descripcion="-",codigo="CS")

    Sub_area.objects.get_or_create(nombre="Ciencias Sociales 1",descripcion="-",area_id=4,codigo="CS1")
    Sub_area.objects.get_or_create(nombre="Educación 1",descripcion="-",area_id=4,codigo="EDU1")

    # Para cargar contenido para el area 5
    Area.objects.get_or_create(id=5,nombre="Congreso de la Sociedad Venezolana de Física",descripcion="-",codigo="CF")

    Sub_area.objects.get_or_create(nombre="Física General",descripcion="-",area_id=5,codigo="FGEN")
    Sub_area.objects.get_or_create(nombre="Óptica y Plasmas",descripcion="-",area_id=5,codigo="OPP")
    Sub_area.objects.get_or_create(nombre="Astronomía",descripcion="-",area_id=5,codigo="AST")
    Sub_area.objects.get_or_create(nombre="Física de Partículas Virtual",descripcion="-",area_id=5,codigo="FPART-V")
    Sub_area.objects.get_or_create(nombre="Cosmología",descripcion="-",area_id=5,codigo="COSM")
    Sub_area.objects.get_or_create(nombre="Materia Condensada Teórica",descripcion="-",area_id=5,codigo="MCT")
    Sub_area.objects.get_or_create(nombre="Instrumentación",descripcion="-",area_id=5,codigo="INST")
    Sub_area.objects.get_or_create(nombre="Física Médica",descripcion="-",area_id=5,codigo="FMED")
    Sub_area.objects.get_or_create(nombre="Física Nuclear",descripcion="-",area_id=5,codigo="FNU")
    Sub_area.objects.get_or_create(nombre="Física de los Materiales",descripcion="-",area_id=5,codigo="FMAT")
    Sub_area.objects.get_or_create(nombre="Física Teórica",descripcion="-",area_id=5,codigo="FTEO")
    Sub_area.objects.get_or_create(nombre="Física del Espacio",descripcion="-",area_id=5,codigo="FESP")


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190820_1442'),
    ]

    operations = [
        migrations.RunPython(load_default_data),
    ]
