# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_default_data_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_asovac',
            name='sedes',
            field=models.TextField(default='Universidad Central de Venezuela', max_length=255),
        ),
    ]
