# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_sistema_asovac_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema_asovac',
            name='slogan',
            field=models.TextField(default='La casa que vence la sombra', max_length=255),
        ),
    ]
