# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-17 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='invitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='palabras',
            field=models.TextField(blank=True, null=True),
        ),
    ]
