# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-19 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20191117_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='pie_pagina',
        ),
        migrations.AddField(
            model_name='resumen',
            name='presidente_cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='presidente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='secretario_cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='secretario_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
