# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20191119_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumen',
            old_name='palabras',
            new_name='presidente_contenido',
        ),
        migrations.AddField(
            model_name='resumen',
            name='secretario_contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
