# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-21 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20191120_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='cabecera',
            field=models.TextField(blank=True, null=True),
        ),
    ]
