# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_resumen_cabecera'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='url_afiche',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
