# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-23 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0007_resumen_url_afiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='afiche_titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
