# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-23 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_resumen_afiche_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='coordinadores_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='miembros_comision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='titulo_comision',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
