# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-18 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_sistema_asovac_slogan'),
        ('recursos', '0009_auto_20191123_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenIndice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac')),
            ],
        ),
    ]
