# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0010_resumenindice'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenindice',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
