# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-25 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import trabajos.models
import trabajos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesiones', '0001_initial'),
        ('arbitrajes', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_version_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_final', models.CharField(default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('se_recibio_version_final_corregida', models.BooleanField(default=False)),
                ('fecha_envio_version_final', models.DateField(default=datetime.datetime.now)),
                ('se_recibio_version_final_presentacion', models.BooleanField(default=False)),
                ('url_version_final_presentacion', models.CharField(max_length=35)),
                ('fecha_envio_version_final_presentacion', models.DateField(blank=True, null=True)),
                ('arbitraje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitraje')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(default='Pendiente', max_length=20)),
                ('titulo_espanol', models.CharField(max_length=100)),
                ('titulo_ingles', models.CharField(blank=True, max_length=100)),
                ('palabras_clave', models.CharField(blank=True, max_length=60)),
                ('forma_presentacion', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20)),
                ('resumen', models.TextField(max_length=255)),
                ('documento_inscrito', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('url_trabajo', models.URLField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('archivo_trabajo', models.FileField(upload_to=trabajos.models.job_directory_path, validators=[trabajos.validators.validate_file_extension])),
                ('requiere_arbitraje', models.BooleanField(default=False)),
                ('padre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo_arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_arbitraje', models.BooleanField(default=False)),
                ('invitacion', models.BooleanField()),
                ('comentario_autor', models.TextField(blank=True)),
                ('arbitraje_resultado', models.CharField(blank=True, max_length=50)),
                ('fecha_arbitraje', models.DateField(blank=True, null=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitro')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='arbitro',
            field=models.ManyToManyField(through='trabajos.Trabajo_arbitro', to='arbitrajes.Arbitro'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.Sesion'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subareas',
            field=models.ManyToManyField(to='main_app.Sub_area'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='trabajo_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo'),
        ),
        migrations.AddField(
            model_name='detalle_version_final',
            name='trabajo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo'),
        ),
    ]
