# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_version_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, max_length=255)),
                ('se_recibio_version_final_corregida', models.BooleanField(default=False)),
                ('url_version_final_trabajo', models.CharField(max_length=35)),
                ('fecha_envio_version_final', models.DateTimeField()),
                ('se_recibio_version_final_presentacion', models.BooleanField(default=False)),
                ('url_version_final_presentacion', models.CharField(max_length=35)),
                ('fecha_envio_version_final_presentacion', models.DateTimeField()),
                ('arbitraje_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitraje')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_espanol', models.CharField(max_length=40)),
                ('titulo_ingles', models.CharField(max_length=40)),
                ('palabras_clave', models.CharField(max_length=40)),
                ('forma_presentacion', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=20)),
                ('subarea1', models.CharField(max_length=20)),
                ('subarea2', models.CharField(max_length=20)),
                ('subarea3', models.CharField(max_length=20)),
                ('arbitro_id', models.ManyToManyField(to='arbitrajes.Arbitro')),
                ('autor_id', models.ManyToManyField(to='autores.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_version_final',
            name='trabajo_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo'),
        ),
    ]
