# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_version_final',
            name='url_version_final_trabajo',
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='area',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subarea1',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subarea2',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subarea3',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='titulo_espanol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='titulo_ingles',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
