# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('arbitrajes', '0002_auto_20190118_0103'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo_arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_arbitraje', models.BooleanField()),
                ('invitacion', models.BooleanField()),
                ('comentario_autor', models.TextField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitro')),
                ('sistema_asovac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac')),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='arbitro_id',
        ),
    ]
