# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
