# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-10 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_version_final',
            name='estatus',
        ),
        migrations.AddField(
            model_name='detalle_version_final',
            name='estatus_final',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalle_version_final',
            name='arbitraje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitraje'),
        ),
        migrations.AlterField(
            model_name='detalle_version_final',
            name='fecha_envio_version_final_presentacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
