# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_version_final',
            old_name='estatus',
            new_name='estatus_final',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
