# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='forma_presentacion',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1),
        ),
    ]
