# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import trabajos.models
import trabajos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='archivo_trabajo',
            field=models.FileField(upload_to=trabajos.models.job_directory_path, validators=[trabajos.validators.validate_file_extension]),
        ),
    ]
