# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-15 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20190512_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
