# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20181229_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='subarea2',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='subarea3',
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Area'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subarea1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sub_area'),
        ),
    ]
