# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20180902_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_version_final',
            name='estatus_final',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalle_version_final',
            name='fecha_envio_version_final',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='detalle_version_final',
            name='fecha_envio_version_final_presentacion',
            field=models.DateField(blank=True),
        ),
    ]
