# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20181001_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='url_trabajo',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
