# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0002_auto_20190118_0103'),
        ('trabajos', '0002_auto_20190209_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='arbitro_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Arbitro'),
        ),
    ]
