# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20180629_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='arbitro_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Arbitro'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='documento_inscrito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='url_trabajo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
