# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_auto_20180926_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_version_final',
            name='fecha_envio_version_final_presentacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
