# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-30 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_trabajo_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_version_final',
            name='arbitraje',
        ),
        migrations.RemoveField(
            model_name='detalle_version_final',
            name='trabajo',
        ),
        migrations.DeleteModel(
            name='Detalle_version_final',
        ),
    ]
