# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-09 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_trabajo_arbitro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo_arbitro',
            name='arbitro',
        ),
        migrations.RemoveField(
            model_name='trabajo_arbitro',
            name='sistema_asovac',
        ),
        migrations.DeleteModel(
            name='Trabajo_arbitro',
        ),
    ]
