# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_auto_20180630_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='autor_id',
        ),
    ]
