# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181230_1547'),
        ('trabajos', '0003_auto_20190103_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='subarea1',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subareas',
            field=models.ManyToManyField(to='main_app.Sub_area'),
        ),
    ]
