# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_auto_20190630_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
