# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_auto_20180926_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_version_final',
            name='arbitraje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitraje'),
        ),
    ]
