# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181230_1547'),
        ('trabajos', '0004_auto_20190103_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='subareas',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subarea1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarea1', to='main_app.Sub_area'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subarea2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subarea2', to='main_app.Sub_area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subarea3',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subarea3', to='main_app.Sub_area'),
            preserve_default=False,
        ),
    ]
