# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_remove_trabajo_autor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_version_final',
            old_name='arbitraje_id',
            new_name='arbitraje',
        ),
        migrations.RenameField(
            model_name='detalle_version_final',
            old_name='trabajo_id',
            new_name='trabajo',
        ),
    ]
