# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0005_auto_20190103_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='subarea1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subarea1', to='main_app.Sub_area'),
            preserve_default=False,
        ),
    ]
