# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0002_auto_20190118_0103'),
        ('trabajos', '0005_auto_20190209_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='arbitro',
            field=models.ManyToManyField(through='trabajos.Trabajo_arbitro', to='arbitrajes.Arbitro'),
        ),
    ]
