# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_trabajo_arbitro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo_arbitro',
            name='comentario_autor',
            field=models.TextField(blank=True),
        ),
    ]
