# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_auto_20190103_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='subarea2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarea2', to='main_app.Sub_area'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='subarea3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subarea3', to='main_app.Sub_area'),
        ),
    ]
