# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0007_auto_20190210_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='trabajo_version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo'),
        ),
    ]
