# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0008_trabajo_trabajo_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='trabajo_version',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajos.Trabajo'),
        ),
    ]
