# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-12 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0011_trabajo_arbitro_arbitraje_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo_arbitro',
            old_name='arbitraje_result',
            new_name='arbitraje_resultado',
        ),
    ]
