# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0012_auto_20190212_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='requiere_arbitraje',
            field=models.BooleanField(default=False),
        ),
    ]
