# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0013_trabajo_requiere_arbitraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo_arbitro',
            name='fecha_arbitraje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
