# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0014_trabajo_arbitro_fecha_arbitraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo_arbitro',
            name='fin_arbitraje',
            field=models.BooleanField(default=False),
        ),
    ]
