# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0015_auto_20190317_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='padre',
            field=models.IntegerField(default=0),
        ),
    ]
