# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0007_auto_20190419_1541'),
        ('trabajos', '0016_trabajo_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.Sesion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='forma_presentacion',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20),
        ),
    ]
