# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0016_trabajo_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='forma_presentacion',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=1),
        ),
    ]
