# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_auto_20190415_1751'),
        ('trabajos', '0016_trabajo_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='sesion',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='sesiones.Sesion'),
            preserve_default=False,
        ),
    ]
