# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0017_auto_20190415_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='forma_presentacion',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=20),
        ),
    ]
