# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0017_trabajo_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.Sesion'),
        ),
    ]
