# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0017_auto_20190421_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='confirmacion_pago',
            field=models.BooleanField(default=False),
        ),
    ]
