# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0018_trabajo_confirmacion_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='confirmacion_pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
