# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0019_auto_20190428_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='confirmacion_pago',
            field=models.CharField(default='Por Revisar', max_length=20),
        ),
    ]
