# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='Sesion',
            new_name='sesion',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='arbitraje',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='coordinadores',
        ),
        migrations.AddField(
            model_name='sesion',
            name='co_coordinador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='coordinador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
