# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-06 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='video_beam',
            new_name='proyector',
        ),
    ]
