# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('sesiones', '0002_auto_20190415_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac'),
            preserve_default=False,
        ),
    ]
