# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_auto_20180727_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='espacio_virtual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.Espacio_virtual'),
        ),
    ]
