# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0003_sesion_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='co_coordinador',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='coordinador',
            field=models.IntegerField(blank=True),
        ),
    ]
