# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_auto_20190415_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='co_coordinador',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='coordinador',
            field=models.IntegerField(default=0),
        ),
    ]
