# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20190116_2313'),
        ('sesiones', '0005_auto_20190415_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinadores_sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador', models.BooleanField(default=False)),
                ('co_coordinador', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.Autor')),
            ],
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='co_coordinador',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='coordinador',
        ),
        migrations.AddField(
            model_name='coordinadores_sesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesiones.Sesion'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='coordinadores',
            field=models.ManyToManyField(through='sesiones.Coordinadores_sesion', to='autores.Autor'),
        ),
    ]
