# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_auto_20190416_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinadores_sesion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autores.Autor'),
        ),
    ]
