# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagador',
            name='categorias_pago',
        ),
        migrations.AddField(
            model_name='datos_pagador',
            name='categorias_pago',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
