# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores_trabajos',
            name='monto_total',
            field=models.FloatField(default=100),
        ),
    ]
