# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-30 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(blank=True, to='main_app.Sistema_asovac'),
        ),
    ]
