# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-02 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_pagador',
            name='categorias_pago',
            field=models.CharField(choices=[('P', 'Personal'), ('I', 'Instituciones'), ('T', 'Terceros')], max_length=20),
        ),
    ]
