# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20190503_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='instituto_investigacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
