# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-02 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20190102_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('T', 'Transferencia'), ('C', 'Cheque')], max_length=1),
        ),
    ]
