# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20180902_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(),
        ),
    ]
