# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_auto_20180628_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='marca_temporal',
            field=models.DateTimeField(blank=True),
        ),
    ]
