# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20180630_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='capitulo_perteneciente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='direccion_envio_correspondencia',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
