# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_auto_20190630_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidad',
            name='instituto_investigacion',
        ),
        migrations.AddField(
            model_name='autor',
            name='instituto_investigacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
