# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0004_auto_20190714_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores_trabajos',
            name='numero_postulacion',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='factura',
            name='postulacion_numero',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
