# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0004_auto_20180908_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagador',
            name='categorias_pago',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
