# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0005_auto_20190803_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores_trabajos',
            name='esperando_modificacion_pago',
            field=models.BooleanField(default=False),
        ),
    ]
