# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0006_auto_20180630_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagador',
            old_name='autor_trabajo_id',
            new_name='autor_trabajo',
        ),
    ]
