# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0006_factura_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_pagador',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(blank=True, to='main_app.Sistema_asovac'),
        ),
    ]
