# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0007_auto_20190806_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='observacion_coordinador',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
