# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0007_auto_20180630_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagador',
            name='autor_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autores.Autores_trabajos'),
        ),
    ]
