# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0008_factura_observacion_coordinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores_trabajos',
            name='numero_postulacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_postulacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
