# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0008_auto_20180630_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='pagador_id',
            new_name='pagador',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='pago_id',
            new_name='pago',
        ),
    ]
