# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0009_auto_20190826_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
