# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0009_auto_20180630_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
