# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180701_2200'),
        ('autores', '0010_auto_20180630_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(to='main_app.Sistema_asovac'),
        ),
        migrations.AddField(
            model_name='datos_pagador',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(to='main_app.Sistema_asovac'),
        ),
    ]
