# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0011_auto_20180702_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='universidad_id',
            new_name='universidad',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
