# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0012_auto_20180703_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autores_trabajos',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='autores_trabajos',
            old_name='trabajo_id',
            new_name='trabajo',
        ),
    ]
