# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(to='main_app.Sistema_asovac'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='arbitraje_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Arbitraje'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='subarea_id',
            field=models.ManyToManyField(to='arbitrajes.Sub_area'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Usuario_asovac'),
        ),
    ]
