# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-30 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_auto_20190630_2358'),
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitro',
            name='arbitraje',
        ),
        migrations.DeleteModel(
            name='Arbitraje',
        ),
    ]
