# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181125_1322'),
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arbitrajes_Sistema_asovac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='arbitro',
            name='Sistema_asovac_id',
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='areas_interes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='clave_arbitro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='datos_institucion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='institucion_trabajo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='arbitrajes_sistema_asovac',
            name='arbitro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrajes.Arbitro'),
        ),
        migrations.AddField(
            model_name='arbitrajes_sistema_asovac',
            name='sistema_asovac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac'),
        ),
    ]
