# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='arbitraje_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Arbitraje'),
        ),
    ]
