# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180826_0223'),
        ('arbitrajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_area',
            name='area_id',
        ),
        migrations.AddField(
            model_name='arbitro',
            name='Sistema_asovac_id',
            field=models.ManyToManyField(to='main_app.Sistema_asovac'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='arbitraje_id',
            field=models.ManyToManyField(blank=True, to='arbitrajes.Arbitraje'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Usuario_asovac'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Sub_area',
        ),
    ]
