# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0002_auto_20180630_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitraje',
            name='marca_temporal',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
