# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0002_auto_20190630_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
    ]
