# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0002_auto_20181229_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='arbitrajes_Sistema_asovac',
            new_name='arbitros_Sistema_asovac',
        ),
    ]
