# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181125_1322'),
        ('arbitrajes', '0003_auto_20181229_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitros_sistema_asovac',
            name='arbitro',
        ),
        migrations.RemoveField(
            model_name='arbitros_sistema_asovac',
            name='sistema_asovac',
        ),
        migrations.RenameField(
            model_name='arbitro',
            old_name='arbitraje_id',
            new_name='arbitraje',
        ),
        migrations.AddField(
            model_name='arbitro',
            name='Sistema_asovac',
            field=models.ManyToManyField(blank=True, to='main_app.Sistema_asovac'),
        ),
        migrations.DeleteModel(
            name='arbitros_Sistema_asovac',
        ),
    ]
