# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-16 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0004_auto_20190913_0315'),
        ('arbitrajes', '0004_auto_20190914_2346'),
    ]

    operations = [
    ]
