# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0004_arbitro_sistema_asovac_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitro',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
