# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0007_auto_20190102_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitro',
            old_name='usuario_asovac',
            new_name='usuario',
        ),
    ]
