# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-06 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrajes', '0009_auto_20190106_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
