# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-27 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
