# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_sistema_asovac_slogan'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='sistema_asovac',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sistema_asovac'),
            preserve_default=False,
        ),
    ]
