# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_organizador_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='url_anuncio_evento',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
