# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20180830_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='capitulo_asovac',
            field=models.CharField(choices=[(0, 'No es mienbro de AsoVAC'), (1, 'Es mienbro de AsoVAC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='genero',
            field=models.SmallIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=0),
        ),
    ]
