# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-06-18 00:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20191128_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='url_anuncio_evento',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
