# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20180830_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='capitulo_asovac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='es_miembro_asovac',
            field=models.BooleanField(choices=[(False, 'No es mienbro de AsoVAC'), (True, 'Es mienbro de AsoVAC')], default=False),
        ),
    ]
