# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20180703_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizador_evento',
            old_name='evento_id',
            new_name='evento',
        ),
        migrations.RenameField(
            model_name='organizador_evento',
            old_name='organizador_id',
            new_name='organizador',
        ),
    ]
