# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 20:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eventos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20180830_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='locacion_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacion_eventos', to='eventos.Locacion_evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador_id',
            field=models.ManyToManyField(related_name='Organizador_eventos', through='eventos.Organizador_evento', to='eventos.Organizador'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='capitulo_asovac',
            field=models.CharField(max_length=50, validators=[eventos.validators.validate_cap_asovac]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='cedula_o_pasaporte',
            field=models.CharField(max_length=20, validators=[eventos.validators.validate_ced_passport]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='correo_electronico',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefono_habitacion_celular',
            field=models.CharField(max_length=20, validators=[eventos.validators.validate_phone_personal]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefono_oficina',
            field=models.CharField(max_length=20, validators=[eventos.validators.validate_phone_office]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='url_organizador',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='usuario_asovac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios_asovac_organizadores', to='main_app.Usuario_asovac'),
        ),
        migrations.AlterField(
            model_name='organizador_evento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='organizador_evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizadores', to='eventos.Organizador'),
        ),
    ]
