# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 21:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180831_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dia_asignado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_preferida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='evento',
            name='url_anuncio_evento',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='locacion_evento',
            name='capacidad_de_asistentes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locacion_evento',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locacion_evento',
            name='equipo_requerido',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locacion_evento',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locacion_evento',
            name='observaciones',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='capitulo_asovac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='cedula_o_pasaporte',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='observaciones',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefono_habitacion_celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefono_oficina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='url_organizador',
            field=models.CharField(max_length=200),
        ),
    ]
